USE wallet;
CREATE TABLE USER(
USER_ID  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
FIRST_NAME VARCHAR(50) NULL,
LAST_NAME  VARCHAR(50) NULL,
EMAIL VARCHAR(50) NULL,
AVAILABLE_BALANCE DOUBLE ,
USER_NAME VARCHAR(50) NOT NULL,
PHONE_NUMBER VARCHAR(50) NULL,
PASSWORD VARCHAR(50) NOT NULL,
DATE_OF_REGISTRATION DATE 
);
sELECT * FROM USER
USE wallet;
CREATE TABLE TRANSACTION(
TRANSACTION_ID  INTEGER NOT NULL AUTO_INCREMENT PRIMARY KEY,
TRANSACTION_NAME VARCHAR(50) NULL,
TRANSACTION_TYPE VARCHAR(10) NOT NULL,
TRANSACTION_AMOUNT DOUBLE,
DATE_OF_TRANSACTION DATE ,
USER_ID INTEGER,
FOREIGN KEY(USER_ID) REFERENCES USER(USER_ID)  
);
sELECT * FROM TRANSACTION